### ISSUE TITLE
SegFault (нашел с большой подсказкой)

### ISSUE THREAD

**Issue by I1Va** [orientiered/cStack#2]
Если сделать в main stk.err = ERR_HASH_DATA, то данные структуры стэка не проверяются хэшами. Можно поломать stk.data
int main(int argc, const char *argv[]) {
    logOpen();
    setLogLevel(L_EXTRA);

    registerFlag(TYPE_BLANK, "-r", "--remove", "Delete old log file");
    processArgs(argc, argv);
    if (isFlagSet("-r")) {
        system("rm log.txt");
        logOpen();
    }

    test2();

    logClose();
}

`void test2() {
    Stack_t stk = {};
    stackCtor(&stk, 10);

    stk.data -= 10;
    stk.err = ERR_HASH_DATA;
    // stk.capacity = 100000;

    stackDump(&stk);
    stackDtor(&stk);

}`

**Comment by orientiered** [comment]
Solved:
Completely removed `err` field from `Stack_t`, so this bug cannot be reproduced now.
Thanks!
